Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Neos.NeosIo.CaseStudies:
            - Main
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Neos.NeosIo.CaseStudies: true

